[global]
keyboard = "de"
country = "de"
fqdn = "${HOST_FQDN}"
mailto = "admin@local"
timezone = "Europe/Berlin"
root_password = "${HOST_PASS_HASH}"
root_ssh_keys = [ "${SSH_KEY}" ]

[network]
source = "from-answer"
cidr = "${HOST_IP}/${HOST_CIDR}" 
gateway = "${HOST_GATEWAY}"
dns = "${HOST_DNS}"
filter.ID_NET_NAME_MAC = "enx785536026c54"

[disk-setup]
filesystem = "ext4"
disk_list = ["${HOST_DISK}"]